<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Copyright>Copyright © Twin Particles</Copyright>
    <Company>Twin Particles</Company>
    <Authors>Twin Particles</Authors>
    <AssemblyName>TwinParticles.CheckEngine.Application</AssemblyName>
    <RootNamespace>TwinParticles.CheckEngine.Application</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwinParticles.CheckEngine.Domain\TwinParticles.CheckEngine.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
  </ItemGroup>

</Project>
