<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Copyright>Copyright © Twin Particles</Copyright>
    <Company>Twin Particles</Company>
    <Authors>Twin Particles</Authors>
    <AssemblyName>TwinParticles.CheckEngine.Infrastructure</AssemblyName>
    <RootNamespace>TwinParticles.CheckEngine.Infrastructure</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwinParticles.CheckEngine.Domain\TwinParticles.CheckEngine.Domain.csproj" />
    <ProjectReference Include="..\..\Libraries\Nop.Data\Nop.Data.csproj" />
    <ProjectReference Include="..\..\Libraries\Nop.Services\Nop.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator.Extensions.SqlServer" Version="7.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Vehicle\Vin\Data\*.json" />
    <EmbeddedResource Include="Vehicle\Admin\Data\*.json" />
  </ItemGroup>

</Project>
