<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Copyright>Copyright © Twin Particles</Copyright>
    <Company>Twin Particles</Company>
    <Authors>Twin Particles</Authors>
    <AssemblyName>TwinParticles.CheckEngine.Domain</AssemblyName>
    <RootNamespace>TwinParticles.CheckEngine.Domain</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
